### ISSUE TITLE
Internal error 

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#235] opened 2015-12-25 09:58 UTC
This doesn't happen all the times but frequently. Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Cannot access the database: Can't connect to MySQL server on '185.52.1.77' (111) (185.52.1.77))

@Southparkfan

**Comment by Southparkfan** [comment] 2015-12-25 11:22
I cannot reproduce this @Reception123.

**Comment by Reception123** [comment] 2015-12-25 12:17
I understand, it only happens sometimes.

**Comment by NDKilla** [comment] 2015-12-28 01:07
This always happens any time the MySQL server OOM's, closing as a known and possibly fixed issue outside of our control (besides server upgrades, which I don't believe this specific issue should cover, and DB optimization, which is kind of continuously mentioned)

**Closed by NDKilla** 2015-12-28 01:07 UTC
