### ISSUE TITLE
Analyze why 502 is continuing

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#162] opened 2015-09-28 03:15 UTC
[SAL](https://meta.miraheze.org/wiki/Tech:Server_admin_log)

>==2015-09-28==
>02:12 revi: restarted HHVM, 502
>01:26 revi: restarted HHVM, 502
>==2015-09-27==
>11:18 revi: restarted HHVM
>08:56 JohnFLewis: restarted hhvm
>04:33 revi: restarted HHVM, was generating 502

Since yesterday, there was 5 HHVM restarts due to 502. (The longest one was 09-27's 01:10~04:33 due to sysadmins' absense. And today, I had to restart HHVM 5 mins after I woke up, and after I ate breakfast.)

We need to know why this is happening since yesterday and try to fix 'em.

**Comment by NDKilla** [comment] 2015-09-28 14:06
I seriously doubt it's related to what I did but I agree this needs to be looked into. It's happening quite often

**Comment by Southparkfan** [comment] 2015-09-28 16:05
Hopefully fixed in 6d1dfa48866ecd1afbd70a4479a0f3edf28e7d6a.

**Comment by JohnFLewis** [comment] 2015-09-28 16:25
http://drunkardswalkforums.yuku.com/reply/132795/All-The-Tropes-Wiki-Project-Part-V#reply-132795 is analysed.

**Comment by revi** [comment] 2015-09-29 03:23
>03:22 revi: restarted HHVM 4mins ago

Ta-da.

**Comment by JohnFLewis** [comment] 2015-09-29 21:24
Possibly a memory leak. Swap usage may be causing the OOMs. Taking as my issue.

**Comment by NDKilla** [comment] 2015-09-30 01:24
@JohnFLewis restarted hhvm again ~10 mins ago.
See on-wiki sysadmin log for timestamp and copy/paste of free -m

**Comment by JohnFLewis** [comment] 2015-09-30 10:21
I spoke with Daniel about this last night informally on IRC and we came to an (also) informal conclusion that the cause is likely a memory leak with HHVM. I rebooted mw1 twice to monitor memory usage. The pattern was usually '30-40% RAM and 30-35% SWAP'. OOMs of HHVM occur usually when swap usage is 90-100% in usage, which align very well with an actual linux OOM as there is no memory left on the VPS.

However... metrics show 95%(!) memory available in actual RAM. Clearly, not a 'real' OOM by numbers but a OOM by theoretic (e.g. memory leaks).

I've looked at common HHVM memory leaking functions and found JIT to be one, which is enabled on Miraheze. I have disabled this (miraheze/puppet@21686f720e56d0d54a063b60846c786a5918cbe1) and swap usage right now 0% (which is correct because it should only swap when there is _NO_ memory left or a process needs too much memory).

I feel this is solved but only time can tell. If this happens again, likely I'll look at seeing if swap got involved at all, if not then we'll need to look at OS-level settings (inc. swap) to figure out why it didn't swap to prevent an OOM. If swap is involved, then its back to the drawing board over whether the only cause is a memory leak or if other factors are involved.

**Comment by JohnFLewis** [comment] 2015-09-30 10:24
numbers of current information for people who like it:

```
root@mw1:~# free -m
             total       used       free     shared    buffers     cached
Mem:           512        376        135         37          0        232
-/+ buffers/cache:        144        367
Swap:          256          0        256
root@mw1:~# uptime -p
up 22 minutes
```

**Comment by JohnFLewis** [comment] 2015-09-30 18:46
We're stable so I'm calling this closed and resolved.

**Closed by JohnFLewis** 2015-09-30 18:46 UTC
Labels: Bug

**Comment by revi** [comment] 2015-10-01 04:34
https://gist.github.com/revi/cad81dc68c19d24def73

Happening again, FYI.

**Comment by JohnFLewis** [comment] 2015-10-01 13:53
Memory data seems regular and fine. The issue isn't occurring frequently so it is solved. One-off incidents can really be ignored if stats are sane otherwise defer to investigating with the HHVM log as MediaWiki-admins (or SPF).
